server:
   port: 8080
spring:
   application:
      name: gateway-service
   cloud:
      gateway:
         routes:
         -  id: product-service
            uri: http://localhost:9050/
            predicates:
            - Path=/v1/product/**
         -  id: recommendation-service
            uri: http://localhost:9060/
            predicates:
            - Path=/v1/recommendation/**
         -  id: review-service
            uri: http://localhost:9070/
            predicates:
            - Path=/v1/review/**
         -  id: product-composite-service
            uri: http://localhost:9070/
            predicates:
            - Path=/v1/productcomposite/**
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka